preset: recommended

risky: true

enabled:
  - concat_with_spaces
  - no_useless_else
  - strict

disabled:
  - concat_without_spaces
  - no_trailing_comma_in_list_call
  - phpdoc_summary
  - post_increment
  - self_accessor

finder:
  not-name:
    - ".phpstorm.meta.php"
    - "CommonMarkCoreExtension.php"
    - "FakeEmptyHtmlRenderer.php"
    - "InlinesOnlyExtension.php"
    - "SmartPunctExtension.php"
    - "TableExtension.php"
  not-path:
    - ".ripstech"
