#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

_decorator()(
    if [ -n "$(command -v docker)" ]; then
        _docker_run webuni/php:7.3 ./run "$@"
    else
        "$@"
    fi
)

# Static analyse
task_analyse()(
    ./vendor/bin/phpstan analyse -l7 src "$@"
    ./vendor/bin/psalm
)

# Run composer
task_composer()(
      composer "$@"
)

# Fix code style
task_cs_fix()(
    ./vendor/bin/php-cs-fixer fix --allow-risky=yes "$@"
)

# Run tests
task_tests()(
    ./vendor/bin/phpunit "$@"
)
