#!/usr/bin/env sh
set -e

# Static analyse
task_analyse()(
    ./vendor/bin/phpstan analyse -l7 src "$@"
    ./vendor/bin/psalm
)

# Fix code style
task_cs_fix()(
    ./vendor/bin/php-cs-fixer fix --allow-risky=yes "$@"
)

# Run tests
task_tests()(
    ./vendor/bin/phpunit "$@"
)

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
! if [ -n "$(command -v 'wget')" ]; then r="$(wget -qT 1 "$url" -O-)" && echo "$r" > .runner; else curl --connect-timeout 1 -fso .runner "$url"; fi
. ./.runner
